# from https://github.com/gitpod-io/gitpod/pull/6409 for host.gateway.internal zz-_48-_y21-1203-2144
experimentalNetwork: true

# use docker image to persist phpstorm ide settings across new workspace or reboot 
#   Simply use `tmy-persist-ide-settings-through-image-for-gitpod` (should be in image already), then get the 
#   latest tag name, update below
#   NOTE: in theory should not need the tag name, but seems gitpod is caching image locally, hence to use 
#   tag name to ensure latest image is pulled
image: tmy2017/gitpod-pm:ver-1639260100

tasks:
  - name: start phpstorm as default 
# use projector run.sh to directly invoke project directory. Thanks to 
#   https://github.com/shaal/DrupalPod/blob/main/.gitpod/utils/phpstorm.template.sh
    command: ~/.projector/configs/PhpStormByIdeAutoinstall-2021.2/run.sh $GITPOD_REPO_ROOT 
# just this directory is different from wildcard zzgosh  zz-_44-_y21-1106-1822
# seems make build will start dc up, which prebuild will just hang, now try only do dc build zz-_44-_y21-1106-1846
  - init: | 
      make deps
      docker-compose build
      docker-compose pull
      sudo chmod o+rwx . 
      sudo chmod -R o+rw *
# since gitpod host machine ip is changing and no host.docker.internal yet, thus must dynamic insert zz-_48-_y21-1203-1943
# also zend_extension = xdebug.so is a must! zz-_48-_y21-1204-0936
    command: |
      docker-compose up 
# split right so normal terminal can be seen  zz-_44-_y21-1107-0714
    openMode: split-right
# direct open preview   
ports:
  # open browser could be blocked by browser
  - port: 19999
    onOpen: open-browser
  - port: 1000-9000
    onOpen: ignore
# still applied even above implicitly says ignore! 
# NOTE: can not have more than two using onOpen: open-preview
  - port: 8041
    visibility: private
    onOpen: open-preview
vscode:
  extensions:
    - https://github.com/jimmygc/linenote-codelens/releases/download/1.0.1/linenote-codelens-1.0.1.vsix
    - bmewburn.vscode-intelephense-client
    - tabnine.tabnine-vscode
    - eamodio.gitlens
    - ms-azuretools.vscode-docker
    - felixfbecker.php-debug
    - alexcvzz.vscode-sqlite
    - humao.rest-client
    - pkief.material-icon-theme
    - alefragnani.bookmarks
    - ms-vscode.live-server