# from https://github.com/gitpod-io/gitpod/pull/6409 for host.gateway.internal zz-_48-_y21-1203-2144
experimentalNetwork: true

image: tmy2017/gitpod-pm

tasks:
  - name: start phpstorm as default 
    command: projector run PhpStormByIdeAutoinstall-2021.2
# just this directory is different from wildcard zzgosh  zz-_44-_y21-1106-1822
# seems make build will start dc up, which prebuild will just hang, now try only do dc build zz-_44-_y21-1106-1846
  - init: | 
      make deps
      docker-compose build
      docker-compose pull
      sudo chmod o+rwx . 
      sudo chmod -R o+rw *
    # since gitpod host machine ip is changing and no host.docker.internal yet, thus must dynamic insert zz-_48-_y21-1203-1943
    # also zend_extension = xdebug.so is a must! zz-_48-_y21-1204-0936
    command: |
      docker-compose up 
# split right so normal terminal can be seen  zz-_44-_y21-1107-0714
    openMode: split-right
# direct open preview   
ports:
  - port: 8041
    visibility: private
    onOpen: open-preview
vscode:
  extensions:
    - https://github.com/jimmygc/linenote-codelens/releases/download/1.0.1/linenote-codelens-1.0.1.vsix
    - bmewburn.vscode-intelephense-client
    - tabnine.tabnine-vscode
    - eamodio.gitlens
    - ms-azuretools.vscode-docker
    - felixfbecker.php-debug
    - alexcvzz.vscode-sqlite
    - humao.rest-client
    - pkief.material-icon-theme
    - alefragnani.bookmarks